### ISSUE TITLE
color is error

### ISSUE THREAD

**Issue by ysfl** [elementary/wingpanel-indicator-session#38]
![2018-02-17 00-58-30](https://user-images.githubusercontent.com/5365219/36321359-90db46d0-1384-11e8-9266-a4042b5a37f5.png)
how to fix the error?
I set it up the menu-have-icons to true,wingpanel select color is white...I can not see the text!!!
Set to false i can not be restored....

**Comment by danrabbit** [comment]
This seems to be an error with your custom stylesheet and not with the session indicator (which is not shown in your screenshot). Please see this question on StackExchange: https://elementaryos.stackexchange.com/questions/13531/ive-changed-my-system-stylesheet-or-icons-and-things-broke-now-what

Closing this issue as "Out of Scope" since it can't be fixed within the codebase of the session indicator
