### ISSUE TITLE
Logout DBus interface not registered [$50]

### ISSUE THREAD

**Issue by danrabbit** [elementary/wingpanel-indicator-session#57]
When the logout shortcut is pressed, the following error appears:

```
Jul 08 14:17:19 HP-Pavilion-Notebook gnome-session[925]: gnome-session-binary[925]: WARNING: Unable to open shell end session dialog: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.gnome.SessionManager.EndSessionDialog' on object at path /org/gnome/SessionManager/EndSessionDialog
Jul 08 14:17:19 HP-Pavilion-Notebook gnome-session-binary[925]: WARNING: Unable to open shell end session dialog: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.gnome.SessionManager.EndSessionDialog' on object at path /org/gnome/SessionManager/EndSessionDialog
```

**Comment by danrabbit** [comment]
It looks like @Philip-Scott previously solved a similar issue many eons ago: https://bugs.launchpad.net/wingpanel-indicator-session/+bug/1610442

**Comment by donadigo** [comment]
Since the entire GNOME Shell interface is implemented in Gala now, we just have to implement this interface within the indicator and make gala forward DBus calls to the indicator.
That's also what Budgie does: https://github.com/solus-project/budgie-desktop/blob/5cd2ad6d211b9e1d02309ea0a531906e12969e5b/src/wm/shim.vala#L20

So we need two PR's, one for gala for forwarding EndSessionDialog DBus calls and one for the session indicator for actually handling them.

**Comment by danrabbit** [comment]
Closing because the wingpanel portion of this was solved.

Gala PR is here: https://github.com/elementary/gala/pull/314

**Comment by vjr** [comment]
Oh my bad, please ignore, I see gala side issue is nearly there.
