### ISSUE TITLE
Produce sound events on Pantheon session log in and log out.

### ISSUE THREAD

**Issue by torikulhabib** [elementary/wingpanel-indicator-session#59]
like description

**Comment by danrabbit** [comment]
I'm not sure that adding sounds here actually notifies the user of some useful event, especially because the time between the greeter and the session is not significant. I can see how this was useful in the days of yore because it might be a long time between login and session, but I think this is a "Design conflict" because it would contribute to notification fatigue.

More thoughts from @elementary/ux ?

**Comment by cassidyjames** [comment]
@danrabbit I agree, the reason for a noise on login seems to stem from the days of a minutes-long login process on a rusty spinning disk. Even on the lowest end supported hardware that elementary OS targets, I don't think the login is anywhere near this long.
