### ISSUE TITLE
Black screen after lock session

### ISSUE THREAD

**Issue by faelz** [elementary/wingpanel-indicator-session#66]
The bug happened after nvidia driver installation. The screen gets black after locking session.

**Comment by peteruithoven** [comment]
Thanks for reporting, this however has nothing to do with the session indicator. 
The report problem button in the About page should help finding the right repo. 

If this happens in the greeter (login screen) I propose you open an issue at: https://github.com/elementary/greeter
Otherwise: https://github.com/elementary/os/
But please clarify a bit more. Does it stay black? Is it the whole screen or just the background? What do you do to get going again?

**Comment by peteruithoven** [comment]
This might be the same issue? https://github.com/elementary/greeter/issues/165
